name: ubuntu (4.0.0)

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - 'blink'
          - 'tim2'
          - 'delay'

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install sdcc
      run: |
        sudo apt update
        sudo apt install -y sdcc

    - name: Build
      working-directory: tests
      run: |
        make ${{ matrix.project }}
