name: ubuntu (4.0.0)

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - 'tim2'
          - 'blink'
          - 'delay'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install sdcc
        run: |
          wget https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/4.0.0/sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
          tar -xf sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
          echo `pwd`/sdcc-4.0.0/bin >> $GITHUB_PATH

      - name: Build
        working-directory: tests
        run: |
          make ${{ matrix.project }}

      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu-sdcc-build
          path: tests/bin
