name: ubuntu (4.0.0)

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Install
      run: |
        wget http://182.61.61.133/dl/sdcc/sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
        tar -xf sdcc-4.0.0-amd64-unknown-linux2.5.tar.bz2
        echo `pwd`/sdcc-4.0.0/bin >> $GITHUB_PATH

    - name: Build
      run: make build
      working-directory: tests
